### ISSUE TITLE
Subscribing to the AbstractFFTs interface

### ISSUE THREAD

**Issue by asinghvi17** [Taaitaaiger/RustFFT.jl#3]
https://github.com/JuliaMath/AbstractFFTs.jl is an interface package for FFTs, used by FFTW.jl and FastTransforms.jl.  At a first glance the RustFFT interface seems similar to that.

It would be pretty cool if this had bindings to AbstractFFTs as well, to make it easier to use and test out!

**Comment by Taaitaaiger** [comment]
That sounds like a great idea to me.

**Comment by jordancluts** [comment]
Was coming to create this same issue. This 100% should be done to allow this implementation to be swapped in for others in the ecosystem.

**Comment by Taaitaaiger** [comment]
AbstractFFTs interface has been implemented :)
